import { Inter } from "next/font/google";
import {Providers} from "./providers";
import NavigationBar from "../../components/header/navbar"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='testing bg-background text-foreground'>
      <body className={inter.className}>
      <Providers>
      <NavigationBar/>
        {children}
      </Providers>
    </body>
  </html>

  );
}
